# Generated by Django 2.1.5 on 2019-06-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competingproductdailysalesforfivedays',
            old_name='tags',
            new_name='firstTags',
        ),
        migrations.AddField(
            model_name='competingproductdailysalesforfivedays',
            name='secondTags',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
