# Generated by Django 2.1.5 on 2019-07-12 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_infringeproductinfo_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infringeproductinfo',
            name='test',
        ),
    ]
