# Generated by Django 2.1.5 on 2019-07-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190712_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infringeproductinfo',
            name='catalog',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='infringeproductinfo',
            name='firstTags',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
