<<<<<<< Updated upstream
# Generated by Django 2.1 on 2019-08-07 03:46
=======
# Generated by Django 2.1 on 2019-08-09 11:21
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catalog',
<<<<<<< Updated upstream
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(default='', max_length=128)),
                ('allCategories', models.CharField(default='', max_length=128)),
                ('firstCategory', models.CharField(default='', max_length=128)),
                ('secondCategory', models.CharField(default='', max_length=128)),
                ('thirdCategory', models.CharField(default='', max_length=128)),
                ('fourthCategory', models.CharField(default='', max_length=128)),
                ('fifthCategory', models.CharField(default='', max_length=128)),
                ('sixthCategory', models.CharField(default='', max_length=128)),
                ('seventhCategory', models.CharField(default='', max_length=128)),
                ('eigthCategory', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='catalogAndtags',
=======
>>>>>>> Stashed changes
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(default='', max_length=128)),
                ('allCategories', models.CharField(default='', max_length=128)),
                ('firstCategory', models.CharField(default='', max_length=128)),
                ('secondCategory', models.CharField(default='', max_length=128)),
                ('thirdCategory', models.CharField(default='', max_length=128)),
                ('fourthCategory', models.CharField(default='', max_length=128)),
                ('fifthCategory', models.CharField(default='', max_length=128)),
                ('sixthCategory', models.CharField(default='', max_length=128)),
                ('seventhCategory', models.CharField(default='', max_length=128)),
                ('eigthCategory', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='competingProductDailySales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.BigIntegerField(verbose_name=64)),
                ('totalSales', models.IntegerField()),
                ('totalEvaluation', models.IntegerField()),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=500)),
                ('productScore', models.CharField(max_length=8)),
                ('price', models.CharField(max_length=64)),
                ('picUrl', models.CharField(max_length=256)),
                ('catalog', models.CharField(default='', max_length=64)),
                ('home', models.CharField(default='', max_length=128)),
                ('allCategories', models.CharField(default='', max_length=128)),
                ('firstCategory', models.CharField(default='', max_length=128)),
                ('secondCategory', models.CharField(default='', max_length=128)),
                ('thirdCategory', models.CharField(default='', max_length=128)),
                ('fourthCategory', models.CharField(default='', max_length=128)),
                ('fifthCategory', models.CharField(default='', max_length=128)),
                ('sixthCategory', models.CharField(default='', max_length=128)),
                ('seventhCategory', models.CharField(default='', max_length=128)),
                ('eigthCategory', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='competingProductDailySalesforFiveDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.BigIntegerField(verbose_name=64)),
                ('catalog', models.CharField(max_length=64, null=True)),
                ('firstTags', models.CharField(max_length=128, null=True)),
                ('secondTags', models.CharField(max_length=128, null=True)),
                ('title', models.CharField(max_length=500)),
                ('totalSales', models.IntegerField()),
                ('totalEvaluation', models.IntegerField()),
                ('productScore', models.CharField(max_length=8)),
                ('price', models.CharField(max_length=64)),
                ('picUrl', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('past1_Sales', models.IntegerField(default=0)),
                ('past2_Sales', models.IntegerField(default=0)),
                ('past3_Sales', models.IntegerField(default=0)),
                ('past4_Sales', models.IntegerField(default=0)),
                ('home', models.CharField(default='', max_length=128)),
                ('allCategories', models.CharField(default='', max_length=128)),
                ('firstCategory', models.CharField(default='', max_length=128)),
                ('secondCategory', models.CharField(default='', max_length=128)),
                ('thirdCategory', models.CharField(default='', max_length=128)),
                ('fourthCategory', models.CharField(default='', max_length=128)),
                ('fifthCategory', models.CharField(default='', max_length=128)),
                ('sixthCategory', models.CharField(default='', max_length=128)),
                ('seventhCategory', models.CharField(default='', max_length=128)),
                ('eigthCategory', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='competingProductInfo',
            fields=[
                ('productId', models.BigIntegerField(primary_key=True, serialize=False, verbose_name=64)),
                ('catalog', models.CharField(max_length=32, null=True)),
                ('firstTags', models.CharField(max_length=128, null=True)),
                ('secondTags', models.CharField(max_length=128, null=True)),
                ('tag', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='infringeProductinfo',
            fields=[
                ('productId', models.BigIntegerField(primary_key=True, serialize=False, verbose_name=64)),
                ('catalog', models.CharField(max_length=32, null=True)),
                ('firstTags', models.CharField(max_length=128, null=True)),
                ('secondTags', models.CharField(max_length=128, null=True)),
                ('totalSales', models.IntegerField()),
                ('totalEvaluation', models.IntegerField()),
                ('productScore', models.CharField(max_length=8)),
                ('price', models.CharField(max_length=64)),
                ('updateDate', models.DateField()),
                ('been_deleted', models.IntegerField(null=True)),
                ('confirm_times', models.IntegerField(null=True)),
<<<<<<< Updated upstream
=======
            ],
        ),
        migrations.CreateModel(
            name='monitorProductTag',
            fields=[
                ('tag', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('comment', models.CharField(default='', max_length=128)),
>>>>>>> Stashed changes
            ],
        ),
        migrations.CreateModel(
            name='newCompetingProductDailySales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.BigIntegerField(verbose_name=64)),
                ('totalSales', models.IntegerField()),
                ('totalEvaluation', models.IntegerField()),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=500)),
                ('productScore', models.CharField(max_length=8)),
                ('price', models.CharField(max_length=64)),
                ('picUrl', models.CharField(max_length=256)),
                ('catalog', models.CharField(max_length=64)),
                ('home', models.CharField(default='', max_length=128)),
                ('allCategories', models.CharField(default='', max_length=128)),
                ('firstCategory', models.CharField(default='', max_length=128)),
                ('secondCategory', models.CharField(default='', max_length=128)),
                ('thirdCategory', models.CharField(default='', max_length=128)),
                ('fourthCategory', models.CharField(default='', max_length=128)),
                ('fifthCategory', models.CharField(default='', max_length=128)),
                ('sixthCategory', models.CharField(default='', max_length=128)),
                ('seventhCategory', models.CharField(default='', max_length=128)),
                ('eigthCategory', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='newCompetingProductInfo',
            fields=[
                ('productId', models.BigIntegerField(primary_key=True, serialize=False, verbose_name=64)),
<<<<<<< Updated upstream
            ],
        ),
        migrations.CreateModel(
            name='preCompetingProductDailySales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.BigIntegerField(verbose_name=64)),
                ('totalSales', models.IntegerField()),
                ('totalEvaluation', models.IntegerField()),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=500)),
                ('productScore', models.CharField(max_length=8)),
                ('price', models.CharField(max_length=64)),
                ('picUrl', models.CharField(max_length=256)),
                ('catalog', models.CharField(max_length=64)),
                ('past1_Sales', models.IntegerField(default=0)),
                ('past2_Sales', models.IntegerField(default=0)),
                ('past3_Sales', models.IntegerField(default=0)),
                ('past4_Sales', models.IntegerField(default=0)),
                ('home', models.CharField(default='', max_length=128)),
                ('allCategories', models.CharField(default='', max_length=128)),
                ('firstCategory', models.CharField(default='', max_length=128)),
                ('secondCategory', models.CharField(default='', max_length=128)),
                ('thirdCategory', models.CharField(default='', max_length=128)),
                ('fourthCategory', models.CharField(default='', max_length=128)),
                ('fifthCategory', models.CharField(default='', max_length=128)),
                ('sixthCategory', models.CharField(default='', max_length=128)),
                ('seventhCategory', models.CharField(default='', max_length=128)),
                ('eigthCategory', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=128, null=True)),
=======
>>>>>>> Stashed changes
            ],
        ),
    ]
