# Generated by Django 2.1.5 on 2019-07-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190626_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='infringeproductinfo',
            name='test',
            field=models.CharField(default='', max_length=128),
        ),
    ]
