# Generated by Django 2.1.5 on 2019-07-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190712_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allCategories', models.CharField(default='', max_length=128)),
                ('firstCategory', models.CharField(default='', max_length=128)),
                ('secondCategory', models.CharField(default='', max_length=128)),
                ('thirdCategory', models.CharField(default='', max_length=128)),
                ('fourthCategory', models.CharField(default='', max_length=128)),
                ('fifthCategory', models.CharField(default='', max_length=128)),
                ('sixthCategory', models.CharField(default='', max_length=128)),
                ('seventhCategory', models.CharField(default='', max_length=128)),
                ('eigthCategory', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='competingproductdailysalesforfivedays',
            name='allCategories',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='competingproductdailysalesforfivedays',
            name='eigthCategory',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='competingproductdailysalesforfivedays',
            name='fifthCategory',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='competingproductdailysalesforfivedays',
            name='firstCategory',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='competingproductdailysalesforfivedays',
            name='fourthCategory',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='competingproductdailysalesforfivedays',
            name='home',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='competingproductdailysalesforfivedays',
            name='secondCategory',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='competingproductdailysalesforfivedays',
            name='seventhCategory',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='competingproductdailysalesforfivedays',
            name='sixthCategory',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='competingproductdailysalesforfivedays',
            name='thirdCategory',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='infringeproductinfo',
            name='been_deleted',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='infringeproductinfo',
            name='confirm_times',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='newcompetingproductdailysales',
            name='allCategories',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='newcompetingproductdailysales',
            name='eigthCategory',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='newcompetingproductdailysales',
            name='fifthCategory',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='newcompetingproductdailysales',
            name='firstCategory',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='newcompetingproductdailysales',
            name='fourthCategory',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='newcompetingproductdailysales',
            name='home',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='newcompetingproductdailysales',
            name='secondCategory',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='newcompetingproductdailysales',
            name='seventhCategory',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='newcompetingproductdailysales',
            name='sixthCategory',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='newcompetingproductdailysales',
            name='thirdCategory',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='precompetingproductdailysales',
            name='allCategories',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='precompetingproductdailysales',
            name='eigthCategory',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='precompetingproductdailysales',
            name='fifthCategory',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='precompetingproductdailysales',
            name='firstCategory',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='precompetingproductdailysales',
            name='fourthCategory',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='precompetingproductdailysales',
            name='home',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='precompetingproductdailysales',
            name='secondCategory',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='precompetingproductdailysales',
            name='seventhCategory',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='precompetingproductdailysales',
            name='sixthCategory',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='precompetingproductdailysales',
            name='thirdCategory',
            field=models.CharField(default='', max_length=128),
        ),
    ]
