# Generated by Django 2.1.5 on 2019-07-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190712_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competingproductdailysales',
            name='catalog',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='competingproductdailysalesforfivedays',
            name='catalog',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='competingproductdailysalesforfivedays',
            name='firstTags',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='competingproductinfo',
            name='catalog',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='competingproductinfo',
            name='firstTags',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
