# Generated by Django 2.1.5 on 2019-07-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190713_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='home',
            field=models.CharField(default='', max_length=128),
        ),
    ]
