# Generated by Django 2.1.5 on 2019-06-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catalogAndtags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog', models.CharField(max_length=32)),
                ('firstTags', models.CharField(max_length=128)),
                ('secondTags', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='competingProductDailySales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.BigIntegerField(verbose_name=64)),
                ('totalSales', models.IntegerField()),
                ('totalEvaluation', models.IntegerField()),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=500)),
                ('productScore', models.CharField(max_length=8)),
                ('price', models.CharField(max_length=64)),
                ('picUrl', models.CharField(max_length=256)),
                ('catalog', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='competingProductDailySalesforFiveDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.BigIntegerField(verbose_name=64)),
                ('catalog', models.CharField(max_length=64)),
                ('tags', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=500)),
                ('totalSales', models.IntegerField()),
                ('totalEvaluation', models.IntegerField()),
                ('productScore', models.CharField(max_length=8)),
                ('price', models.CharField(max_length=64)),
                ('picUrl', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('past1_Sales', models.IntegerField(default=0)),
                ('past2_Sales', models.IntegerField(default=0)),
                ('past3_Sales', models.IntegerField(default=0)),
                ('past4_Sales', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='competingProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.BigIntegerField(verbose_name=64)),
                ('catalog', models.CharField(max_length=32)),
                ('firstTags', models.CharField(max_length=128)),
                ('secondTags', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='infringeProductinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.BigIntegerField(verbose_name=64)),
                ('catalog', models.CharField(max_length=32)),
                ('firstTags', models.CharField(max_length=128)),
                ('secondTags', models.CharField(max_length=128, null=True)),
                ('totalSales', models.IntegerField()),
                ('totalEvaluation', models.IntegerField()),
                ('productScore', models.CharField(max_length=8)),
                ('price', models.CharField(max_length=64)),
                ('createdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='newCompetingProductDailySales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.BigIntegerField(verbose_name=64)),
                ('totalSales', models.IntegerField()),
                ('totalEvaluation', models.IntegerField()),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=500)),
                ('productScore', models.CharField(max_length=8)),
                ('price', models.CharField(max_length=64)),
                ('picUrl', models.CharField(max_length=256)),
                ('catalog', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='newCompetingProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.BigIntegerField(verbose_name=64)),
            ],
        ),
        migrations.CreateModel(
            name='preCompetingProductDailySales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.BigIntegerField(verbose_name=64)),
                ('totalSales', models.IntegerField()),
                ('totalEvaluation', models.IntegerField()),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=500)),
                ('productScore', models.CharField(max_length=8)),
                ('price', models.CharField(max_length=64)),
                ('picUrl', models.CharField(max_length=256)),
                ('catalog', models.CharField(max_length=64)),
                ('past1_Sales', models.IntegerField(default=0)),
                ('past2_Sales', models.IntegerField(default=0)),
                ('past3_Sales', models.IntegerField(default=0)),
                ('past4_Sales', models.IntegerField(default=0)),
            ],
        ),
    ]
