# Generated by Django 2.1.5 on 2019-07-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190712_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='competingproductinfo',
            name='tag',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
