# Generated by Django 2.1.5 on 2019-07-12 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190712_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infringeproductinfo',
            old_name='createdate',
            new_name='updateDate',
        ),
    ]
