# Generated by Django 2.1.5 on 2019-07-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_catalog_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competingproductinfo',
            name='tag',
            field=models.CharField(default='', max_length=128),
        ),
    ]
